/*
 * Nightbot command:
 * !editcom -ul=everyone -cd=30 !randomsong $(eval $(urlfetch json https://raw.githubusercontent.com/PhilHoff84/broughy1322/master/twitch-sings.js); randomSong('$(query)');)
 */
function randomSong(query) {
    /* Sanitize the filter criteria specified in the query */
    query = normalize(query);

    /* Print usage */
    if (query === 'usage') {
        return 'Usage: !randomsong (<artist> | all)';
    }

    /* Find all songs that match the specified criteria */
    var songs = all().filter(function (song) {
        return song.matches(query);
    });

    /* Output a random song (or error message) */
    if (songs.length > 0) {
        var song = songs[Math.floor(Math.random() * songs.length)];
        return 'Random song 1/' + songs.length + ': ' + song;
    } else {
        return 'Could not find a matching random song ¯\\_(ツ)_/¯';
    }
}

function normalize(text) {
    if (!text) {
        text = '';
    }

    /* Convert to lowercase */
    text = ('' + text).toLowerCase();

    /* Remove plural */
    text = text.replace(/s\b/g, '');

    /* Remove accents */
    text = text.normalize('NFD').replace(/[\u0300-\u036f]/g, '');

    /* Remove all chars that are not letters, digits or blanks */
    text = text.replace(/[^a-z0-9 ]+/g, '');

    /* Substitute common aliases with the correct criteria */
    switch (text) {
        case '': /* Print usage, if there was not even a single valid letter in the text */
        case 'help':
        case 'option':
        case 'instruction':
            return 'usage';
        default:
            return text;
    }
}

function Song(title, artist) {
    this.artist = artist;
    this.title = title;

    this.toString = function () {
        return artist + ' - ' + title;
    };

    this.matches = function (query) {
        switch (query) {
            /* Random song from any genre and year */
            case 'all':
                return true;
            /* Random song that matches the specified genre, artist or year */
            case normalize(artist):
                return true;
            default:
                return false;
        }
    };
}

function all() {
    return [
        new Song("Here Without You", "3 Doors down"),
        new Song("Kryptonite", "3 Doors down"),
        new Song("Landing In London", "3 Doors down"),
        new Song("Candy Store", "50 Cent"),
        new Song("In Da Club(Clean)", "50 Cent"),
        new Song("One Less Bell to Answer", "5th Dimension, The"),
        new Song("Almost Lover", "A Fine Frenzy"),
        new Song("Almost Lover", "A Fine Frenzy"),
        new Song("I Ran (So Far Away)", "A Flock of Seagulls"),
        new Song("I Ran (So Far Away)", "A Flock of Seagulls"),
        new Song("Rock The Boat", "Aaliyah"),
        new Song("We Need A Resolution", "Aaliyah"),
        new Song("Chiquitita", "ABBA"),
        new Song("Honey, Honey", "ABBA"),
        new Song("I Do, I Do, I Do, I Do, I Do", "ABBA"),
        new Song("Knowing Me, Knowings You", "ABBA"),
        new Song("Ring Ring", "ABBA"),
        new Song("S.O.S.", "ABBA"),
        new Song("The Name Of The Game", "ABBA"),
        new Song("When All Is Said And Done", "ABBA"),
        new Song("Back in Black", "AC/DC"),
        new Song("Big Balls", "AC/DC"),
        new Song("Dirty Deeds Done Dirt Cheap", "AC/DC"),
        new Song("For Those About To Rock (We Salute You)", "AC/DC"),
        new Song("Have a Drink on Me", "AC/DC"),
        new Song("Hells Bells", "AC/DC"),
        new Song("It's a long way to the top (If you wanna rock n' roll)", "AC/DC"),
        new Song("Shoot to thrill", "AC/DC"),
        new Song("T.N.T.", "AC/DC"),
        new Song("Thunderstruck", "AC/DC"),
        new Song("Whole Lotta Rosie", "AC/DC"),
        new Song("You Shook Me All Night Long", "AC/DC"),
        new Song("The Sign", "Ace Of Base"),
        new Song("Pulled", "Addams Family, The (Musical)"),
        new Song("Cryin'", "Aerosmith"),
        new Song("Dream On", "Aerosmith"),
        new Song("Sweet Emotion", "Aerosmith"),
        new Song("Walk This Way", "Aerosmith"),
        new Song("Because I Got High", "Afroman"),
        new Song("All Out Of Love", "Air Supply"),
        new Song("Let's Stay Together", "Al Green"),
        new Song("Love And Happiness", "Al Green"),
        new Song("Angels Among Us", "Alabama"),
        new Song("Forever's as Far as I'll Go", "Alabama"),
        new Song("Old Flame", "Alabama"),
        new Song("The Closer You Get", "Alabama"),
        new Song("A Whole New World", "Aladdin"),
        new Song("Arabian Nights", "Aladdin"),
        new Song("Prince Ali", "Aladdin"),
        new Song("Friend Like Me", "Aladdin (Musical)"),
        new Song("One Jump Ahead", "Aladdin (Musical)"),
        new Song("Chattahoochee", "Alan Jackson"),
        new Song("Gone Country", "Alan Jackson"),
        new Song("Here in the Real World", "Alan Jackson"),
        new Song("I Don't Even Know Your Name", "Alan Jackson"),
        new Song("Little Bitty", "Alan Jackson"),
        new Song("Livin' on Love", "Alan Jackson"),
        new Song("Mercury Blues", "Alan Jackson"),
        new Song("Midnight in Montgomery", "Alan Jackson"),
        new Song("Pop A Top", "Alan Jackson"),
        new Song("Summertime Blues", "Alan Jackson"),
        new Song("Uninvited", "Alanis Morissette"),
        new Song("Hallelujah", "Alexandra Burke"),
        new Song("Down In A Hole", "Alice In Chains"),
        new Song("Rooster", "Alice In Chains"),
        new Song("Would?", "Alice In Chains"),
        new Song("Fallin'", "Alicia Keys"),
        new Song("If I Ain't Got You", "Alicia Keys"),
        new Song("Dirty Little Secret", "All-American Rejects, The"),
        new Song("Gives You Hell", "All-American Rejects, The"),
        new Song("Swing, Swing", "All-American Rejects, The"),
        new Song("Ramblin' Man", "Allman Brothers Band, The"),
        new Song("A Horse with No Name", "America"),
        new Song("Sister Golden Hair", "America"),
        new Song("Ventura Highway", "America"),
        new Song("Knock On Wood", "Amii Stewart"),
        new Song("Mr. Rock and Roll", "Amy Macdonald"),
        new Song("This Is The Life", "Amy Macdonald"),
        new Song("Back to Black (Acoustic)", "Amy Winehouse"),
        new Song("Love Is a Losing Game", "Amy Winehouse"),
        new Song("Rehab", "Amy Winehouse"),
        new Song("Tears Dry On Their Own", "Amy Winehouse"),
        new Song("You Know I'm No Good", "Amy Winehouse"),
        new Song("Rise Up", "Andra Day"),
        new Song("When I Fall in Love", "Andrea Bocelli"),
        new Song("I'll Be With You In Apple Blossom Time", "Andrews Sisters, The"),
        new Song("Oh Johnny, Oh Johnny, Oh!", "Andrews Sisters, The"),
        new Song("Caught Up in the Rapture", "Anita Baker"),
        new Song("Sweet Love", "Anita Baker"),
        new Song("Could i have this Dance", "Anne Murray"),
        new Song("Daydream Believer", "Anne Murray"),
        new Song("I Just Fall In Love Again", "Anne Murray"),
        new Song("Best of Me", "Anthony Hamilton"),
        new Song("Chain of Fools", "Aretha Franklin"),
        new Song("I Say A Little Prayer", "Aretha Franklin"),
        new Song("Satisfaction", "Aretha Franklin"),
        new Song("Bang Bang", "Ariana Grande"),
        new Song("Break Free", "Ariana Grande"),
        new Song("Dangerous Woman", "Ariana Grande"),
        new Song("Bright Eyes", "Art Garfunkel "),
        new Song("Heat Of The Moment", "Asia"),
        new Song("Never My Love", "Association, The"),
        new Song("Secret Lovers", "Atlantic Starr"),
        new Song("The Boys Light Up", "Australian Crawl"),
        new Song("Complicated", "Avril Lavigne"),
        new Song("I'm With You", "Avril Lavigne"),
        new Song("Sk8er Boi", "Avril Lavigne"),
        new Song("Love Shack", "B-52, The"),
        new Song("Hooked On A Feeling", "B. J. Thomas"),
        new Song("Raindrops Keep Fallin' On My Head", "B. J. Thomas"),
        new Song("Takin' Care Of Business", "Bachman-Turner Overdrive"),
        new Song("I Want It That Way", "Backstreet Boys"),
        new Song("Larger Than Life", "Backstreet Boys"),
        new Song("Quit Playing Games (With my Heart)", "Backstreet Boys"),
        new Song("Zombie", "Bad Wolves"),
        new Song("Do They Know It's Christmas?", "Band Aid"),
        new Song("Up on Cripple Creek", "Band, The"),
        new Song("Don't Rain On My Parade", "Barbra Streisand"),
        new Song("The Way We Were", "Barbra Streisand"),
        new Song("If I Had 1000000 dollars", "Barenaked Ladies"),
        new Song("One Week", "Barenaked Ladies"),
        new Song("The Old Apartment", "Barenaked Ladies"),
        new Song("Copacabana", "Barry Manilow"),
        new Song("Even Now", "Barry Manilow"),
        new Song("I Write The Songs", "Barry Manilow"),
        new Song("Can't Get Enough Of Your Love Babe", "Barry White"),
        new Song("Just The Way You Are", "Barry White"),
        new Song("You're The First, The Last, My Everything", "Barry White"),
        new Song("Pompeii", "Bastille"),
        new Song("Barbara Ann", "Beach Boys, The"),
        new Song("Kokomo", "Beach Boys, The"),
        new Song("Brass Monkey", "Beastie Boys"),
        new Song("Intergalactic", "Beastie Boys"),
        new Song("Paul Revere", "Beastie Boys"),
        new Song("A Day in the Life", "Beatles, The"),
        new Song("A Hard Day's Night", "Beatles, The"),
        new Song("All My Love", "Beatles, The"),
        new Song("All You Need Is Love", "Beatles, The"),
        new Song("And I Love Her", "Beatles, The"),
        new Song("Back in the U.S.S.R.", "Beatles, The"),
        new Song("Because", "Beatles, The"),
        new Song("Birthday", "Beatles, The"),
        new Song("Blackbird", "Beatles, The"),
        new Song("Can't Buy Me Love", "Beatles, The"),
        new Song("Day Tripper", "Beatles, The"),
        new Song("Dear Prudence", "Beatles, The"),
        new Song("Do You Want To Know A Secret", "Beatles, The"),
        new Song("Don't Let Me Down", "Beatles, The"),
        new Song("Drive My Car", "Beatles, The"),
        new Song("Eleanor Rigby", "Beatles, The"),
        new Song("For No One", "Beatles, The"),
        new Song("Get Back", "Beatles, The"),
        new Song("Good Day Sunshine", "Beatles, The"),
        new Song("Got To Get You Into My Life", "Beatles, The"),
        new Song("Hello Goodbye", "Beatles, The"),
        new Song("Here, There And Everyone", "Beatles, The"),
        new Song("Honey Pie", "Beatles, The"),
        new Song("I am the Walrus", "Beatles, The"),
        new Song("I Feel Fine", "Beatles, The"),
        new Song("I Should Have Known Better", "Beatles, The"),
        new Song("I Will", "Beatles, The"),
        new Song("I'll Follow the Sun", "Beatles, The"),
        new Song("I'm So Tired", "Beatles, The"),
        new Song("I've Got A Feeling", "Beatles, The"),
        new Song("I've Just Seen a Face", "Beatles, The"),
        new Song("If I Fell", "Beatles, The"),
        new Song("In My Life", "Beatles, The"),
        new Song("It's Only Love", "Beatles, The"),
        new Song("Lady Madonna", "Beatles, The"),
        new Song("Lucy in the Sky with Diamonds", "Beatles, The"),
        new Song("Maxwell's Silver Hammer", "Beatles, The"),
        new Song("Michelle", "Beatles, The"),
        new Song("Norwegian Wood", "Beatles, The"),
        new Song("Nowhere Man", "Beatles, The"),
        new Song("Ob-La-Di, Ob-La-Da", "Beatles, The"),
        new Song("Oh! Darling", "Beatles, The"),
        new Song("One After 909", "Beatles, The"),
        new Song("Paperback Writer", "Beatles, The"),
        new Song("Penny Lane", "Beatles, The"),
        new Song("Rocky Raccoon", "Beatles, The"),
        new Song("Sgt. Pepper's Lonely Hearts Club Band", "Beatles, The"),
        new Song("Strawberry Fields Forever", "Beatles, The"),
        new Song("The Ballad Of John and Yoko", "Beatles, The"),
        new Song("The Fool on the Hill", "Beatles, The"),
        new Song("The Night Before", "Beatles, The"),
        new Song("Things We Said Today", "Beatles, The"),
        new Song("This Boy", "Beatles, The"),
        new Song("Ticket to Ride", "Beatles, The"),
        new Song("Till There Was You", "Beatles, The"),
        new Song("Twist and Shout", "Beatles, The"),
        new Song("We Can Work It Out", "Beatles, The"),
        new Song("You Can't Do That", "Beatles, The"),
        new Song("You Never Give Me Your Money", "Beatles, The"),
        new Song("You've Got to Hide Your Love Away", "Beatles, The"),
        new Song("Be Our Guest", "Beauty and The Beast"),
        new Song("Beauty and The Beast", "Beauty and The Beast"),
        new Song("Gaston", "Beauty and The Beast"),
        new Song("Something There", "Beauty and The Beast"),
        new Song("Loser", "Beck"),
        new Song("Stand By Me", "Ben E. King"),
        new Song("You Don't Know Me", "Ben Folds"),
        new Song("From A Distance", "Bette Midler"),
        new Song("The Rose", "Bette Midler"),
        new Song("Promise Me", "Beverley Craven"),
        new Song("At Last", "Beyoncé"),
        new Song("Blow", "Beyoncé"),
        new Song("Baby, I Love Your Way", "Big Mountain"),
        new Song("Use Me", "Bill Withers"),
        new Song("Blanket On The Ground", "Billie Jo Spears"),
        new Song("Mony Mony", "Billy Idol"),
        new Song("Honesty", "Billy Joel"),
        new Song("It's Still Rock & Roll To Me", "Billy Joel"),
        new Song("Just The Way You Are", "Billy Joel"),
        new Song("Movin' Out (Anthony's Song)", "Billy Joel"),
        new Song("My Life", "Billy Joel"),
        new Song("New York State Of Mind", "Billy Joel"),
        new Song("Only The Good Die Young", "Billy Joel"),
        new Song("Piano Man", "Billy Joel"),
        new Song("River Of Dreams", "Billy Joel"),
        new Song("Scenes From An Italian Restaurant", "Billy Joel"),
        new Song("She's Always a Woman", "Billy Joel"),
        new Song("She's Got A Way", "Billy Joel"),
        new Song("The Longest Time", "Billy Joel"),
        new Song("Uptown Girl", "Billy Joel"),
        new Song("We Didn't Start The Fire", "Billy Joel"),
        new Song("You May Be Right", "Billy Joel"),
        new Song("Carribean Queen (No More Love On The Run)", "Billy Ocean"),
        new Song("Love Really Hurts Without You", "Billy Ocean"),
        new Song("Suddenly", "Billy Ocean"),
        new Song("Me and Mrs. Jones", "Billy Paul"),
        new Song("Achy Breaky Heart", "Billy Ray Cyrus"),
        new Song("Wher'm I Gonna Live", "Billy Ray Cyrus"),
        new Song("At This Moment", "Billy Vera"),
        new Song("People Help the People", "Birdy"),
        new Song("Skinny Love", "Birdy"),
        new Song("River", "Bishop Briggs"),
        new Song("Hard To Handle", "Black Crowes, The"),
        new Song("She Talks To Angels", "Black Crowes, The"),
        new Song("My Humps", "Black Eyed Peas"),
        new Song("Iron Man", "Black Sabbath"),
        new Song("Paranoid", "Black Sabbath"),
        new Song("Snowblind", "Black Sabbath"),
        new Song("War Pigs", "Black Sabbath"),
        new Song("Honey Bee", "Blake Shelton"),
        new Song("All The Small Things", "Blink-182"),
        new Song("What's My Age Again?", "Blink-182"),
        new Song("Heart Of Glass", "Blondie"),
        new Song("One Way Or Another", "Blondie"),
        new Song("The Bad Touch", "Bloodhound Gang, The"),
        new Song("Minnie The Moocher", "Blues Brothers, The"),
        new Song("Soul Man", "Blues Brothers, The"),
        new Song("Song 2", "Blur"),
        new Song("Could You Be Loved", "Bob Marley"),
        new Song("Is This Love", "Bob Marley"),
        new Song("Jamming", "Bob Marley"),
        new Song("No Woman, No Cry", "Bob Marley"),
        new Song("Stir It Up", "Bob Marley"),
        new Song("Three Little Birds", "Bob Marley"),
        new Song("Waiting In Vain", "Bob Marley"),
        new Song("Mack The Knife", "Bobby Darin"),
        new Song("Rockin' Robbin", "Bobby Day"),
        new Song("Fraulein", "Bobby Helms"),
        new Song("My Special Angel", "Bobby Helms"),
        new Song("Don't Worry, Be Happy", "Bobby McFerrin"),
        new Song("Feliz Navidad", "Boney M."),
        new Song("Angel from Montgomery", "Bonnie Raitt"),
        new Song("I'll Make Love To You", "Boys II Men"),
        new Song("It's So Hard To Say Goodbye To Yesterday", "Boys II Men"),
        new Song("The Story", "Brandi Carlile"),
        new Song("The Boy Is Mine", "Brandy"),
        new Song("If", "Bread"),
        new Song("Make It With You", "Bread"),
        new Song("Sweet Nothin's", "Brenda Lee"),
        new Song("Back At One", "Brian McKnight"),
        new Song("…Baby One More Time", "Britney Spears"),
        new Song("Circus", "Britney Spears"),
        new Song("Everytime", "Britney Spears"),
        new Song("Gimme More", "Britney Spears"),
        new Song("Kill The Lights", "Britney Spears"),
        new Song("Lucky", "Britney Spears"),
        new Song("Slumber Party", "Britney Spears"),
        new Song("Boot Scootin' Boogie", "Brooks & Dunn"),
        new Song("My Maria", "Brooks & Dunn"),
        new Song("My Next Broken Heart", "Brooks & Dunn"),
        new Song("Neon Moon", "Brooks & Dunn"),
        new Song("You're Gonna Miss Me When I'm Gone", "Brooks & Dunn GUYS THIS IS NOT THE CUPS SONG"),
        new Song("It Ain't My Fault", "Brothers Osborne"),
        new Song("Shoot Me Straight", "Brothers Osborne"),
        new Song("Chunky", "Bruno Mars"),
        new Song("That's What I Like", "Bruno Mars"),
        new Song("Versace On The Floor (VS David Guetta)", "Bruno Mars"),
        new Song("When I Was Your Man", "Bruno Mars"),
        new Song("Back To You", "Bryan Adams"),
        new Song("Act Naturally", "Buck Owens"),
        new Song("Heartbeat", "Buddy Holly"),
        new Song("Maybe Baby", "Buddy Holly"),
        new Song("Oh, Boy!", "Buddy Holly"),
        new Song("Peggy Sue", "Buddy Holly"),
        new Song("True Love Ways", "Buddy Holly"),
        new Song("Comedown", "Bush"),
        new Song("Glycerine", "Bush"),
        new Song("I Will Survive", "Cake"),
        new Song("The Distance", "Cake"),
        new Song("Dancing on My Own", "Calum Scott"),
        new Song("Young Hearts Run Free", "Candi Staton"),
        new Song("Do That To Me One More Time", "Captain & Tenille"),
        new Song("Lovefool", "Cardigans, The"),
        new Song("Kung Fu Fighting", "Carl Douglas"),
        new Song("Every Little Thing", "Carly Pearce"),
        new Song("Call Me Maybe", "Carly Rae Jepsen"),
        new Song("Mockingbird", "Carly Simon"),
        new Song("You're So Vain", "Carly Simon"),
        new Song("I Feel The Earth Move", "Carole King"),
        new Song("(They Long To Be) Close to You", "Carpenters, The"),
        new Song("I Won't Last a Day Without You", "Carpenters, The"),
        new Song("Only Yesterday", "Carpenters, The"),
        new Song("Please Mr. Postman", "Carpenters, The"),
        new Song("Rainy Days and Mondays", "Carpenters, The"),
        new Song("Sweet, Sweet Smile", "Carpenters, The"),
        new Song("Top of the World", "Carpenters, The"),
        new Song("Yesterday Once More", "Carpenters, The"),
        new Song("Church Bells", "Carrie Underwood"),
        new Song("Dirty Laundry", "Carrie Underwood"),
        new Song("Hark! The Herald Angels Sing", "Carrie Underwood"),
        new Song("The First Noel", "Carrie Underwood"),
        new Song("Wasted", "Carrie Underwood"),
        new Song("Rhythm of the Rain", "Cascades, The"),
        new Song("Father and Son", "Cat Stevens "),
        new Song("Moonshadow", "Cat Stevens "),
        new Song("Morning Has Broken", "Cat Stevens "),
        new Song("Wild World", "Cat Stevens "),
        new Song("Finally", "Ce Ce Peniston"),
        new Song("It's All Coming Back To Me Now", "Céline Dion"),
        new Song("Ain't Nobody", "Chaka Khan"),
        new Song("Devil Went Down to Georgia", "Charlie Daniels Band, The"),
        new Song("Drinkin' My Baby Goodbye", "Charlie Daniels Band, The"),
        new Song("Attention", "Charlie Puth"),
        new Song("How Long", "Charlie Puth"),
        new Song("Marvin Gaye", "Charlie Puth"),
        new Song("One Call Away", "Charlie Puth"),
        new Song("The Most Beautiful Girl", "Charlie Rich"),
        new Song("I Want You To Want Me", "Cheap Trick"),
        new Song("Gypsys, Tramps & Thieves", "Cher"),
        new Song("Walking In Memphis", "Cher"),
        new Song("Le Freak", "Chic"),
        new Song("All That Jazz", "Chicago (The Movie)"),
        new Song("When You're Good To Mama", "Chicago (The Musical)"),
        new Song("Deck The Halls", "Children's Chorus"),
        new Song("O Little Town of Bethlehem", "Children's Chorus"),
        new Song("We Three Kings", "Children's Chorus"),
        new Song("The Lady In Red", "Chris De Burgh"),
        new Song("Wicked Game", "Chris Isaak"),
        new Song("Driving Home For Christmas", "Chris Rea"),
        new Song("Fool (If You Think It's Over)", "Chris Rea"),
        new Song("Josephine", "Chris Rea"),
        new Song("On The Beach", "Chris Rea"),
        new Song("The Road to Hell", "Chris Rea"),
        new Song("Millionaire", "Chris Stapleton"),
        new Song("Parachute", "Chris Stapleton"),
        new Song("The Man I Want to Be", "Chris Young"),
        new Song("Merry Christmas, Baby", "Christina Aguilera"),
        new Song("Human", "Christina Perri"),
        new Song("Jar Of Hearts", "Christina Perri"),
        new Song("Carol of the Bells", "Christmas Carol"),
        new Song("Douce nuit, sainte nuit", "Christmas Carol"),
        new Song("It Came Upon A Midnight Clear", "Christmas Carol"),
        new Song("Jingle Bells", "Christmas Carol"),
        new Song("Silent Night (Man Voice)", "Christmas Carol"),
        new Song("Silent Night (Woman Voice)", "Christmas Carol"),
        new Song("The Christmas Song (Chestnuts Roasting)", "Christmas Carol"),
        new Song("Twelve Days of Christmas", "Christmas Carol"),
        new Song("Ride Like The Wind", "Christopher Cross"),
        new Song("Sailing", "Christopher Cross"),
        new Song("Johnny B. Goode", "Chuck Berry"),
        new Song("No Particular Place To Go", "Chuck Berry"),
        new Song("You Never Can Tell", "Chuck Berry"),
        new Song("The Mother We Share", "Chvches"),
        new Song("A Dream is a Wish Your Heart Makes", "Cinderella (The Musical)"),
        new Song("Bibbidi-Bobbidi-Boo", "Cinderella (The Musical)"),
        new Song("(I Don't Know Why) But I Do", "Clarence \"Frogman\" Henry"),
        new Song("Rather Be", "Clean Bandit"),
        new Song("Blue Suede Shoes", "Cliff Richard"),
        new Song("The Young Ones", "Cliff Richard"),
        new Song("We Don't Talk Anymore", "Cliff Richard"),
        new Song("A Better Man", "Clint Black"),
        new Song("Killin' Time", "Clint Black"),
        new Song("La Llorona", "Coco"),
        new Song("Remember Me", "Coco"),
        new Song("Bubbly", "Colbie Caillat"),
        new Song("Sail on", "Commodores, The"),
        new Song("Three Times a Lady", "Commodores, The"),
        new Song("Lipstick On Your Collar", "Connie Francis"),
        new Song("Don't Cry Joni", "Conway Twitty"),
        new Song("Hello Darlin'", "Conway Twitty"),
        new Song("It's Only Make Believe", "Conway Twitty"),
        new Song("Linda on My Mind", "Conway Twitty"),
        new Song("Slow Hand", "Conway Twitty"),
        new Song("Like A Virgin", "Cooltrane Quartet, The"),
        new Song("Zombie", "Cranberries, The"),
        new Song("Mmm, Mmm, Mmm, Mmm", "Crash Test Dummies"),
        new Song("Don't Stop Dancing", "Creed"),
        new Song("Hide", "Creed"),
        new Song("Higher", "Creed"),
        new Song("My Own Prison", "Creed"),
        new Song("My Sacrifice", "Creed"),
        new Song("One Last Breath", "Creed"),
        new Song("Bad Moon Rising", "Creedence Clearwater Revival"),
        new Song("Proud Mary", "Creedence Clearwater Revival"),
        new Song("Cold", "Crossfade"),
        new Song("Better Be Home Soon", "Crowded House"),
        new Song("Don't Dream It's Over", "Crowded House "),
        new Song("Da Doo Ron Ron", "Crystals, The"),
        new Song("Then He Kissed Me", "Crystals, The"),
        new Song("Lil' Devil", "Cult, The"),
        new Song("Rain", "Cult, The"),
        new Song("She Sells Sanctuary", "Cult, The"),
        new Song("Do You Really Want To Hurt Me", "Culture Club"),
        new Song("Karma Chameleon", "Culture Club"),
        new Song("Boys Don't Cry", "Cure, The"),
        new Song("Friday I'm in Love", "Cure, The"),
        new Song("Lullaby", "Cure, The"),
        new Song("(I Just) Died In Your Arms", "Cutting Crew"),
        new Song("I Drove all Night", "Cyndi Lauper"),
        new Song("Tequila", "Dan + Shay"),
        new Song("Beautiful Sunday", "Daniel Boone"),
        new Song("At The Hop", "Danny and the Juniors"),
        new Song("Mother", "Danzig"),
        new Song("Don't Wait", "Dashboard Confessional"),
        new Song("Hands Down", "Dashboard Confessional"),
        new Song("Stolen", "Dashboard Confessional"),
        new Song("Please Come To Boston", "Dave Loggins"),
        new Song("Space Oddity", "David Bowie"),
        new Song("Babylon", "David Gray"),
        new Song("Titanium", "David Guetta"),
        new Song("Titanium (Acoustic)", "David Guetta"),
        new Song("Just A Gigolo/I Ain't Got Nobody", "David Lee Roth"),
        new Song("You Spin Me Round (Like A Record)", "Dead or Alive"),
        new Song("Baby, It's Cold Outside", "Dean Martin"),
        new Song("King Of The Road", "Dean Martin"),
        new Song("On the Street Where you Live", "Dean Martin"),
        new Song("True Love", "Dean Martin"),
        new Song("Only Us", "Dear Evan Hansen"),
        new Song("Sincerely Me", "Dear Evan Hansen"),
        new Song("Waving Through a Window", "Dear Evan Hansen"),
        new Song("I Will Follow You Into The Dark", "Death Cab For Cutie"),
        new Song("Soul Meets Body", "Death Cab for Cutie"),
        new Song("Breakfast At Tiffany's ", "Deep Blue Something"),
        new Song("Animal", "Def Leppard"),
        new Song("Hysteria", "Def Leppard"),
        new Song("Love Bites", "Def Leppard"),
        new Song("Photograph", "Def Leppard"),
        new Song("Pour Some Sugar on Me", "Def Leppard"),
        new Song("Runaway", "Del Shannon"),
        new Song("Change (In the House of Flies)", "Deftones"),
        new Song("Confident", "Demi Lovato"),
        new Song("Cool for the Summer", "Demi Lovato"),
        new Song("Let It Go (Electronic Dance Remix)", "Demi Lovato"),
        new Song("Stone Cold", "Demi Lovato"),
        new Song("You Gotta Be", "Des'Ree"),
        new Song("All On Me", "Devin Dawson"),
        new Song("Whip It", "Devo"),
        new Song("Come On Eileen", "Dexys Midnight Runners"),
        new Song("The Look Of Love", "Diana Krall"),
        new Song("Upside Down", "Diana Ross"),
        new Song("The Wanderer", "Dion"),
        new Song("I'll Never Fall In Love Again", "Dionne Warwick"),
        new Song("Walk On By", "Dionne Warwick"),
        new Song("Down With The Sickness", "Disturbed"),
        new Song("Stricken", "Disturbed"),
        new Song("The Light", "Disturbed"),
        new Song("Cowboy Take Me Away", "Dixie Chicks"),
        new Song("Goodbye Earl", "Dixie Chicks"),
        new Song("Not Ready To Make Nice", "Dixie Chicks"),
        new Song("Wide Open Spaces", "Dixie Chicks"),
        new Song("Chapel of Love", "Dixie Cups, The"),
        new Song("Summertime", "DJ Jazzy Jeff & The Fresh Prince"),
        new Song("Hey Baby", "DJ Ötzi"),
        new Song("The Gambler", "DJ Ötzi"),
        new Song("Cake by the Ocean", "DNCE"),
        new Song("Drift Away", "Dobie Gray"),
        new Song("Tenessee Waltz", "Don Gibson"),
        new Song("American Pie", "Don McLean"),
        new Song("Vincent", "Don McLean"),
        new Song("(Turn Out The Light And) Love Me Tonight", "Don Williams"),
        new Song("I Believe In You", "Don Williams"),
        new Song("You're My Best Friend", "Don Williams"),
        new Song("Listen to the Music", "Doobie Brothers, The"),
        new Song("Sexy Eyes", "Dr. Hook & The Medicine Show"),
        new Song("And I Am Telling You I'm Not Going", "Dreamgirls"),
        new Song("Come on Over to my Place", "Drifters, The"),
        new Song("Saturday Night at the Movies", "Drifters, The"),
        new Song("You're More Than a Number In My Little Red Book", "Drifters, The"),
        new Song("Bodies", "Drowning Pool"),
        new Song("Tear Away", "Drowing Pool"),
        new Song("IDGAF", "Dua Lipa"),
        new Song("New Rules", "Dua Lipa"),
        new Song("Mercy", "Duffy "),
        new Song("Warwick Avenue", "Duffy "),
        new Song("Honky Tonk Man", "Dwight Yoakam"),
        new Song("Turn It On, Turn It Up, Turn Me Loose", "Dwight Yoakam"),
        new Song("Save Tonight", "Eagle-Eye Cherry"),
        new Song("Love Will Keep Us Alive", "Eagle, The"),
        new Song("Peaceful Easy Feeling", "Eagle, The"),
        new Song("Holding Her And Loving You", "Earl Thomas Conley"),
        new Song("Shining Star", "Earth, Wind & Fire"),
        new Song("Make It Rain (from Sons Of Anarchy)", "Ed Sheeran"),
        new Song("Take Me Home Tonight", "Eddie Money"),
        new Song("Drivin' My Life Away", "Eddie Rabbitt"),
        new Song("I Love A Rainy Night", "Eddie Rabbitt"),
        new Song("Make The World Go Away", "Eddy Arnold"),
        new Song("I'll Be", "Edwin McCain"),
        new Song("We Don't Have To Take Our Clothes Off", "Ella Eyre"),
        new Song("Cry Me A River", "Ella Fitzgerald"),
        new Song("It Don't Mean A Thing", "Ella Fitzgerald"),
        new Song("I Told You I Was Mean", "Elle King"),
        new Song("Love Me Like You Do", "Ellie Goulding"),
        new Song("Grandma Got Run Over By A Reindeer", "Elmo & Patsy"),
        new Song("Bennie And The Jets", "Elton John"),
        new Song("Blue Eyes", "Elton John"),
        new Song("Don't Go Breaking My Heart", "Elton John"),
        new Song("Don't Let The Sun Go Down On Me (Duet)", "Elton John"),
        new Song("I Guess That's Why They Call It The Blues", "Elton John"),
        new Song("I'm Still Standing", "Elton John"),
        new Song("Nikita", "Elton John"),
        new Song("Sacrifice", "Elton John"),
        new Song("Something About The Way You Look Tonight", "Elton John"),
        new Song("Sorry Seems To Be The Hardest Word", "Elton John"),
        new Song("(There'll Be) Peace in the Vally (For Me)", "Elvis Presley"),
        new Song("Always On My Mind", "Elvis Presley"),
        new Song("American Trilogy", "Elvis Presley"),
        new Song("An American Trilogy (with the Royal Philharmonic Orchstra)", "Elvis Presley"),
        new Song("And I Love You So", "Elvis Presley"),
        new Song("Baby, What You Want Me To Do", "Elvis Presley"),
        new Song("Blue Suede Shoes", "Elvis Presley"),
        new Song("Burning Love", "Elvis Presley"),
        new Song("Burning Love (Live '73)", "Elvis Presley"),
        new Song("Can't Help Falling in Love", "Elvis Presley"),
        new Song("Don't", "Elvis Presley"),
        new Song("Don't Cry Daddy", "Elvis Presley"),
        new Song("Green, Green Grass of Home", "Elvis Presley"),
        new Song("Heartbreak Hotel", "Elvis Presley"),
        new Song("Jailhouse Rock", "Elvis Presley"),
        new Song("Love Me", "Elvis Presley"),
        new Song("Loving You", "Elvis Presley"),
        new Song("My Way", "Elvis Presley"),
        new Song("O Come, All Ye Faithful", "Elvis Presley"),
        new Song("Santa Claus Is Back in Town (with the Royal Philharmonic Orchestra)", "Elvis Presley"),
        new Song("Silent Night", "Elvis Presley"),
        new Song("Suspicious Minds", "Elvis Presley"),
        new Song("That's All Right", "Elvis Presley"),
        new Song("Treat Me nice", "Elvis Presley"),
        new Song("Trouble", "Elvis Presley"),
        new Song("Until It's Time For You To Go", "Elvis Presley"),
        new Song("You Gave Me A Mountain", "Elvis Presley"),
        new Song("Don't Let Go (Love)", "En Vogue"),
        new Song("(You Never Can Tell) C'est la Vie", "Emmylou Harris"),
        new Song("A Man Without Love", "Engelbert Humperdinck"),
        new Song("The Way It Used To Be", "Engelbert Humperdinck"),
        new Song("Bailamos", "Enrique Inglesias"),
        new Song("Hero", "Enrique Inglesias"),
        new Song("Hero (Radio Version)", "Enrique Inglesias"),
        new Song("Drink In My Hand", "Eric Church"),
        new Song("Smoke A Little Smoke", "Eric Church"),
        new Song("Before You Accuse Me", "Eric Clapton"),
        new Song("Cocaine", "Eric Clapton"),
        new Song("I Shot The Sherrif", "Eric Clapton"),
        new Song("Tulsa Time", "Eric Clapton"),
        new Song("On & On", "Erykah Badu"),
        new Song("All I Could Do Was Cry", "Etta James"),
        new Song("At Last", "Etta James"),
        new Song("Damn Your Eyes", "Etta James"),
        new Song("I Just Want To Make Love To You", "Etta James"),
        new Song("I'd Rather Go Blind", "Etta James"),
        new Song("Songbird", "Eva Cassidy"),
        new Song("Wade In The Water", "Eva Cassidy"),
        new Song("Bring Me to Life", "Evanescence"),
        new Song("Call Me When You're Sober", "Evanescence"),
        new Song("Going Under", "Evanescence"),
        new Song("My Immortal", "Evanescence"),
        new Song("Sweet Sacrifice", "Evanescence"),
        new Song("Inside Out", "Eve 6"),
        new Song("What It's Like", "Everlast"),
        new Song("Let It Be Me", "Everly Brothers, The"),
        new Song("Walk Right Back", "Everly Brothers, The"),
        new Song("More Than Words", "Extreme"),
        new Song("It Matters to Me", "Faith Hill"),
        new Song("Dance, Dance", "Fall Out Boy"),
        new Song("My Songs Know What You Did In The Dark", "Fall Out Boy"),
        new Song("Sugar, We're Going Down", "Fall Out Boy"),
        new Song("The Phoenix", "Fall Out Boy"),
        new Song("This Ain't a Scene, It's an Arms Race", "Fall Out Boy"),
        new Song("Hello Walls", "Faron Young"),
        new Song("Trap Queen", "Fetty Wap"),
        new Song("Almost Lover", "Fine Frenzy, A"),
        new Song("Bad Company", "Five Finger Death Punch"),
        new Song("Far From Home", "Five Finger Death Punch"),
        new Song("Gone Away", "Five Finger Death Punch"),
        new Song("Jekyll And Hyde", "Five Finger Death Punch"),
        new Song("Lift Me Up", "Five Finger Death Punch"),
        new Song("Wash It All Away", "Five Finger Death Punch"),
        new Song("Wrong Side Of Heaven", "Five Finger Death Punch"),
        new Song("Superman (It's Not Easy)", "Five for Fighting"),
        new Song("In The Still of the Night", "Five Satins, The"),
        new Song("Don't Stop", "Fleetwood Mac"),
        new Song("Dreams", "Fleetwood Mac"),
        new Song("Everywhere", "Fleetwood Mac"),
        new Song("Go Your Own Way", "Fleetwood Mac"),
        new Song("Gold Dust Woman", "Fleetwood Mac"),
        new Song("Landslide", "Fleetwood Mac"),
        new Song("Little Lies", "Fleetwood Mac"),
        new Song("Monday Morning", "Fleetwood Mac"),
        new Song("Second Hand News", "Fleetwood Mac"),
        new Song("Low", "Flo Rida"),
        new Song("I Ran (So Far Away)", "Flock of Seagulls, A"),
        new Song("Dog Days Are over", "Florence + The Machine"),
        new Song("H.O.L.Y.", "Florida Georgia Line"),
        new Song("Fully Alive", "Flyleaf"),
        new Song("Everlong", "Foo Fighters"),
        new Song("The Pretender", "Foo Fighters"),
        new Song("I Can't Help myself (Sugar Pie, Honey Bunch)", "Four Tops, The"),
        new Song("Super Rich Kids", "Frank Ocean"),
        new Song("Bad, Bad Leroy Brown", "Frank Sinatra"),
        new Song("I Get a Kick Out Of You", "Frank Sinatra"),
        new Song("I Only Have Eyes for You", "Frank Sinatra"),
        new Song("I've Got the World on a String", "Frank Sinatra"),
        new Song("Love's Been Good to Me", "Frank Sinatra"),
        new Song("Luck Be a Lady", "Frank Sinatra"),
        new Song("Mack The Knife", "Frank Sinatra"),
        new Song("New York, New York", "Frank Sinatra"),
        new Song("One For My Baby", "Frank Sinatra"),
        new Song("Strangers In The Night", "Frank Sinatra"),
        new Song("Summer Wind (Solo)", "Frank Sinatra"),
        new Song("The Lady Is a Tramp", "Frank Sinatra"),
        new Song("The Way You Look Tonight", "Frank Sinatra"),
        new Song("Witchcraft", "Frank Sinatra"),
        new Song("You Make Me Feel So Young", "Frank Sinatra"),
        new Song("Beauty School Dropout", "Frankie Avalon"),
        new Song("Sunshine & Whiskey", "Frankie Ballard"),
        new Song("Relax", "Frankie Goes To Hollywood"),
        new Song("The Power Of Love", "Frankie Goes to Hollywood"),
        new Song("Take Me Out", "Franz Ferdinand"),
        new Song("Chelsea Dagger", "Fratellis, The"),
        new Song("All Right Now", "Free"),
        new Song("Do You Want to Build a Snowman", "Frozen"),
        new Song("For the First Time in Forever", "Frozen"),
        new Song("In Summer", "Frozen"),
        new Song("Love is an Open Door", "Frozen"),
        new Song("Hemmorhage (In My Hands)", "Fuel"),
        new Song("Some Nights", "Fun"),
        new Song("Sweet About Me", "Gabriella Cilmi"),
        new Song("Only Happy When It Rains", "Garbage"),
        new Song("Callin' Baton Rouge", "Garth Brooks"),
        new Song("Friends In Low Places", "Garth Brooks"),
        new Song("Shameless", "Garth Brooks"),
        new Song("The Dance", "Garth Brooks"),
        new Song("Smoke Rings In The Dark", "Gary Allan"),
        new Song("Still Got The Blues", "Gary Moore"),
        new Song("Walking By Myself", "Gary Moore"),
        new Song("Nothing's Gonna Change My Love For You", "George Benson"),
        new Song("Blame It On Me", "George Ezra"),
        new Song("Hold My Girl", "George Ezra"),
        new Song("Paradise", "George Ezra"),
        new Song("Pretty Shining People", "George Ezra"),
        new Song("Shotgun", "George Ezra"),
        new Song("Golden Ring", "George Jones"),
        new Song("Grand Tour", "George Jones"),
        new Song("He Stopped Loving Her Today", "George Jones"),
        new Song("Tennessee Whiskey", "George Jones"),
        new Song("The One I Loved Back Then", "George Jones"),
        new Song("Who's Gonna Fill Their Shoes", "George Jones"),
        new Song("Ace In The Hole", "George Strait"),
        new Song("All My Ex's Live In Texas", "George Strait"),
        new Song("Amarillo by Morning", "George Strait"),
        new Song("Carrying Your Love With Me", "George Strait"),
        new Song("Drinking Champagne", "George Strait"),
        new Song("Marina del Rey", "George Strait"),
        new Song("The Chair", "George Strait"),
        new Song("The Fireman", "George Strait"),
        new Song("When Did You Stop Loving Me", "George Strait"),
        new Song("You Look So Good In Love", "George Strait"),
        new Song("Bad To The Bone", "George Thorogood"),
        new Song("I Drink Alone", "George Thorogood"),
        new Song("One Bourbon, One Scotch, One Beer", "George Thorogood"),
        new Song("Keep Your Hands to Yourself", "Georgia Satellites, The"),
        new Song("Ferry Cross The Mersey", "Gerry & The Pacemakers"),
        new Song("Baker Street", "Gerry Rafferty"),
        new Song("Square Hammer", "Ghost"),
        new Song("Hey Jealousy", "Gin Blossoms"),
        new Song("Pony", "Ginuwine"),
        new Song("Midnight Train to Georgia", "Gladys Knight & The Pips"),
        new Song("Galveston", "Glen Campbell"),
        new Song("Gentle On My Mind", "Glen Campbell"),
        new Song("Wichita Lineman", "Glen Campbell"),
        new Song("Turn the Beat Around", "Gloria Estefan"),
        new Song("I Will Survive", "Gloria Gaynor"),
        new Song("I Hate U, I love U", "Gnash"),
        new Song("I Stand Alone", "Godsmack"),
        new Song("Voodoo", "Godsmack"),
        new Song("Iris", "Goo Goo Dolls"),
        new Song("If You Could Read My Mind", "Gordon Lightfoot"),
        new Song("Sundown", "Gordon Lightfoot"),
        new Song("The Wreak of the Edmund Fitzgerald", "Gordon Lightfoot"),
        new Song("Heavy Cross", "Gossip, The"),
        new Song("Move in the Right Direction", "Gossip, The"),
        new Song("Somebody That I Used To Know", "Gotye"),
        new Song("These Eyes", "Guess Who, The"),
        new Song("Since I Don't Have You", "Guns N' Roses"),
        new Song("Sympathy For The Devil", "Guns N' Roses"),
        new Song("Balada Boa", "Gusttavo Lima"),
        new Song("What Is Love", "Haddaway"),
        new Song("Love Myself", "Hailee Steinfeld"),
        new Song("Starving", "Hailee Steinfeld"),
        new Song("I Can't Go For That (No Can Do)", "Hall & Oates"),
        new Song("Rich Girl", "Hall & Oates"),
        new Song("You Make My Dreams ", "Hall & Oates"),
        new Song("Him & I", "Halsey"),
        new Song("Now or Never", "Halsey"),
        new Song("Hey, Good Lookin'", "Hank Williams, Jr."),
        new Song("Cold Cold Heart", "Hank Williams, Sr."),
        new Song("Jambalaya (One the Bayou)", "Hank Williams, Sr."),
        new Song("Barracuda", "Heart"),
        new Song("We Wish You a Merry Christmas", "Helene Fischer"),
        new Song("I Won't Say (I'm in Love)", "Hercules"),
        new Song("Breaking Free", "High School Musical"),
        new Song("My Name is Human", "Highly Suspect"),
        new Song("Daddy's Hands", "Holly Dunn"),
        new Song("Hold My Hand", "Hootie And The Blowfish"),
        new Song("Let Her Cry", "Hootie And The Blowfish"),
        new Song("Only Wanna Be With You", "Hootie And The Blowfish"),
        new Song("You Sexy Thing", "Hot Chocolate"),
        new Song("Let it Go", "Idina Menzel"),
        new Song("Believer", "Imagine Dragons"),
        new Song("I Bet My Life", "Imagine Dragons"),
        new Song("It's Time", "Imagine Dragons"),
        new Song("Next to Me", "Imagine Dragons"),
        new Song("On Top Of The World", "Imagine Dragons"),
        new Song("Thunder", "Imagine Dragons"),
        new Song("Whatever It Takes", "Imagine Dragons"),
        new Song("The Unicorn", "Irish Rovers, The"),
        new Song("For the Love of You", "Isley Brothers, The"),
        new Song("You're Only Lonely", "J. D. Souther"),
        new Song("ABC", "Jackson 5, The"),
        new Song("Blame it On the Boogie", "Jackson 5, The"),
        new Song("I Want You Back", "Jackson 5, The"),
        new Song("I'll Be There", "Jackson 5, The"),
        new Song("Hold Back The River", "James Bay"),
        new Song("Get Up Offa That Thing", "James Brown"),
        new Song("Handy Man", "James Taylor"),
        new Song("Control", "Janet Jackson"),
        new Song("Nasty", "Janet Jackson"),
        new Song("Í'll Need Someone To Hold Me (When I Cry)", "Janie Fricke"),
        new Song("Trumpets", "Jason Derulo"),
        new Song("Want to Want Me", "Jason Derulo"),
        new Song("Harper Vally P.T.A.", "Jeannie C. Riley"),
        new Song("Angel Eyes", "Jeff Healey Band, The"),
        new Song("Let's Get Loud", "Jennifer Lopez"),
        new Song("Don't Be So Hard on Yourself", "Jess Glynne"),
        new Song("You Got It All", "Jet, The"),
        new Song("Locomotive Breath", "Jethro Tull"),
        new Song("A Long Walk", "Jill Scott"),
        new Song("I'll Have To Say I Love You In A Song", "Jim Croce"),
        new Song("You Don't Mess Around With Jim", "Jim Croce"),
        new Song("He'll Have To Go", "Jim Reeves"),
        new Song("I Love You Because", "Jim Reeves"),
        new Song("A Pirate Looks At Forty", "Jimmy Buffett"),
        new Song("Come Monday", "Jimmy Buffett"),
        new Song("Big Bad John", "Jimmy Dean"),
        new Song("Bleed American", "Jimmy Eat World"),
        new Song("Pain", "Jimmy Eat World"),
        new Song("Sweetness", "Jimmy Eat World"),
        new Song("Work", "Jimmy Eat World"),
        new Song("I Love Rock 'N Roll", "Joan Jett"),
        new Song("You Are So Beautiful", "Joe Cocker"),
        new Song("Rose Colored Glasses", "John Conlee"),
        new Song("Back Home Again", "John Denver"),
        new Song("Some Days Are Diamonds", "John Denver"),
        new Song("Take Me Home, Country Roads", "John Denver"),
        new Song("Thank God I'm a Country Boy", "John Denver"),
        new Song("Boom Boom", "John Lee Hooker"),
        new Song("Imagine", "John Lennon"),
        new Song("Love Me Again", "John Newman"),
        new Song("Love is in the Air", "John Paul Young"),
        new Song("(Ghost) Riders In The Sky", "Johnny Cash"),
        new Song("Boy Named Sue", "Johnny Cash"),
        new Song("Cocaine Blues", "Johnny Cash"),
        new Song("Get Rhythm", "Johnny Cash"),
        new Song("God's Gonna Cut You Down", "Johnny Cash"),
        new Song("Guess Things Happen That Way", "Johnny Cash"),
        new Song("Hurt ", "Johnny Cash"),
        new Song("I Walk The Live", "Johnny Cash"),
        new Song("Ring of Fire", "Johnny Cash"),
        new Song("Rusty Cage", "Johnny Cash"),
        new Song("North To Alaska", "Johnny Horton"),
        new Song("Head Over Boots", "Jon Pardi"),
        new Song("Mama", "Jonas Blue"),
        new Song("Why Don't We Just Dance", "Josh Turner"),
        new Song("Jessie", "Joshua Kadison"),
        new Song("Right to Be Wrong", "Joss Stone"),
        new Song("Love Will Tear Us Apart", "Joy Division"),
        new Song("Grandpa (Tell Me 'Bout the Good Old Days)", "Judds, The"),
        new Song("Have Mercy", "Judds, The"),
        new Song("The Ripper", "Judas Priest"),
        new Song("Victim Of Changes", "Judas Priest"),
        new Song("The Sweetest Thing (I've Ever Known)", "Juice Newton"),
        new Song("Heaven", "Julia Michaels"),
        new Song("Worst in Me", "Julia Michaels"),
        new Song("I Wan'na Be Like You (The Monkey Song)", "Jungle Book, The"),
        new Song("The Bare Necessities", "Jungle Book, The"),
        new Song("Be Alright", "Justin Bieber"),
        new Song("Beauty and A Beat", "Justin Bieber"),
        new Song("Boyfriend", "Justin Bieber"),
        new Song("Sorry", "Justin Bieber"),
        new Song("What Do You Mean?", "Justin Bieber"),
        new Song("Blowin' Smoke", "Kacey Musgraves"),
        new Song("Way Down We Go", "Kaleo"),
        new Song("Carry On Wayward Son", "Kansas"),
        new Song("Brokenhearted", "Karmin"),
        new Song("Get Down Tonight", "KC & The Sunshine Band"),
        new Song("That's The Way (I Like It)", "KC & The Sunshine Band"),
        new Song("Piece By Piece (Live)", "Kelly Clarkson"),
        new Song("You And Tequila", "Kenny Chesney"),
        new Song("Coward Of The County", "Kenny Rogers"),
        new Song("The Gambler", "Kenny Rogers"),
        new Song("Dumas Walker", "Kentucky Headhunters, The"),
        new Song("Oh Lonesome Me", "Kentucky Headhunters, The"),
        new Song("Singing the Blues", "Kentucky Headhunters, The"),
        new Song("Walk Softly on this Heart of Mine", "Kentucky Headhunters, The"),
        new Song("Praying", "Kesha"),
        new Song("Woman", "Kesha"),
        new Song("Young, Dumb & Broke", "Khalid"),
        new Song("Use Somebody", "Kings of Leon"),
        new Song("Lola", "Kinks, The"),
        new Song("Detroit Rock City", "Kiss"),
        new Song("Heaven's On Fire", "Kiss"),
        new Song("Lick It Up", "Kiss"),
        new Song("Rock and Roll All Nite", "Kiss"),
        new Song("Strutter", "Kiss"),
        new Song("Celebration", "Kool And The Gang"),
        new Song("Fresh ", "Kool And The Gang"),
        new Song("Ladies Night", "Kool And The Gang"),
        new Song("Sunday Mornin' Comin' Down", "Kris Kristofferson"),
        new Song("Do Ya'", "K.T. Oslin"),
        new Song("Our Truth", "Lacuna Coil"),
        new Song("Heart Break", "Lady Antebellum"),
        new Song("You Look Good", "Lady Antebellum"),
        new Song("Bad Romance", "Lady Gaga"),
        new Song("The Edge Of Glory", "Lady Gaga"),
        new Song("You And I", "Lady Gaga"),
        new Song("Blue Jeans", "Lana Del Rey"),
        new Song("Born to Die", "Lana Del Rey"),
        new Song("Summertime Sadness", "Lana Del Rey"),
        new Song("Video Games", "Lana Del Rey"),
        new Song("Young & Beautiful", "Lana Del Rey"),
        new Song("Greatest Love Story", "LANco"),
        new Song("One In A Million You", "Larry Graham"),
        new Song("Doo Wop (That Thing)", "Lauryn Hill"),
        new Song("Ex-Factor", "Lauryn Hill"),
        new Song("I Like Me Better", "Lauv"),
        new Song("All My Friends", "LCD Soundsystem"),
        new Song("God Bless The U.S.A.", "Lee Greenwood"),
        new Song("Again", "Lenny Kravitz"),
        new Song("Always on the Run", "Lenny Kravitz"),
        new Song("Low", "Lenny Kravitz"),
        new Song("Hallelujah", "Leonard Cohen"),
        new Song("Get Low (Clean)", "Lil' Jon"),
        new Song("Prayer in C", "Lilly Wood & The Prick"),
        new Song("Behind Blue Eyes", "Limp Bizkit"),
        new Song("My Way", "Limp Bizkit"),
        new Song("Nookie", "Limp Bizkit"),
        new Song("Blue Bayou", "Linda Ronstadt"),
        new Song("Different Drum", "Linda Ronstadt"),
        new Song("When Will I Be Loved?", "Linda Ronstadt"),
        new Song("Be Prepared", "Lion King, The"),
        new Song("Can You Feel the Love Tonight", "Lion King, The"),
        new Song("Cicle of Life", "Lion King, The"),
        new Song("Hakuna Matata", "Lion King, The"),
        new Song("I Just Can't Wait to be King", "Lion King, The"),
        new Song("Hallelujah (acoustic)", "Lisa Lois"),
        new Song("My Own Worst Enemy", "Lit"),
        new Song("Your Side of the Bed", "Little Big Town"),
        new Song("Kiss the Girl", "Little Mermaid, The"),
        new Song("Les Poissons", "Little Mermaid, The"),
        new Song("Part of Your World", "Little Mermaid, The"),
        new Song("Poor Unfortunate Souls", "Little Mermaid, The"),
        new Song("Under the Sea", "Little Mermaid, The"),
        new Song("Cool Change", "Little River Band"),
        new Song("Reminiscing", "Little River Band"),
        new Song("Suddenly Seymour", "Little Shop of Horrors"),
        new Song("Lightning Crashes", "Live"),
        new Song("Cult Of Personality", "Living Colour"),
        new Song("Me and You and a Dog Named Boo", "Lobo"),
        new Song("Your Mama Don't Dance", "Loggins and Messina"),
        new Song("Strong", "London Grammar"),
        new Song("Brandy (You're a Fine Girl)", "Looking Glass"),
        new Song("The Night We Met", "Lord Huron"),
        new Song("Green Light", "Lorde"),
        new Song("Royals", "Lorde"),
        new Song("Except For Monday", "Lorrie Morgan"),
        new Song("Five Minutes", "Lorrie Morgan"),
        new Song("Black Is Black", "Los Bravos"),
        new Song("Are You with Me", "Lost Frequencies"),
        new Song("Lady Love", "Lou Rawls"),
        new Song("Walk On The Wild Side", "Lou Reed"),
        new Song("Working For The Weekend", "Loverboy"),
        new Song("Lost On You", "LP"),
        new Song("Move", "Luke Bryan"),
        new Song("Ho Hey", "Lumineers, The"),
        new Song("Bills", "LunchMoney Lewis"),
        new Song("Free Bird", "Lynyrd Skynyrd"),
        new Song("Gimme Three Steps", "Lynyrd Skynyrd"),
        new Song("Sweet Home Alabama", "Lynyrd Skynyrd"),
        new Song("That Smell", "Lynyrd Skynyrd"),
        new Song("The Ballad Of Curtis Loew", "Lynyrd Skynyrd"),
        new Song("Tuesday's Gone", "Lynyrd Skynyrd"),
        new Song("Borderline", "Madonna"),
        new Song("Rude", "MAGIC!"),
        new Song("California Dreamin'", "Mamas and the Papas, The"),
        new Song("I Call Your Name", "Mamas and The Papas, The"),
        new Song("Monday, Monday", "Mamas and the Papas, The"),
        new Song("Kiss and Say Goodbye", "Manhattans, The"),
        new Song("Sex And Candy", "Marcy Playground"),
        new Song("All I Want For Christmas Is You", "Mariah Carey"),
        new Song("Always Be My Baby", "Mariah Carey"),
        new Song("Hero", "Mariah Carey"),
        new Song("Let Me Love You", "Mario"),
        new Song("Return Of The Mack", "Mark Morrison"),
        new Song("Harder To Breathe", "Maroon 5"),
        new Song("One More Night", "Maroon 5"),
        new Song("Sunday Morning", "Maroon 5"),
        new Song("This Love", "Maroon 5"),
        new Song("Independence Day", "Martina McBride"),
        new Song("A Broken Wing", "Martina McBridge"),
        new Song("Concrete Angel", "Martina McBridge"),
        new Song("A White Sport Coat (And A Pink Carnation)", "Marty Robbins"),
        new Song("Devil Woman", "Marty Robbins"),
        new Song("El Paso", "Marty Robbins"),
        new Song("Red River Valley", "Marty Robbins"),
        new Song("Ain't No Mountain High Enough", "Marvin Gaye"),
        new Song("Ain't That Peculiar", "Marvin Gaye"),
        new Song("I Heard It Through The Grapvine", "Marvin Gaye"),
        new Song("Let's Get It On", "Marvin Gaye"),
        new Song("Sexual Healing", "Marvin Gaye"),
        new Song("What's Going On", "Marvin Gaye"),
        new Song("Down At The Twist And Shout", "Mary Chapin Carpenter"),
        new Song("A Spoonful of Sugar", "Mary Poppins"),
        new Song("Chim Chim Cher-ee", "Mary Poppins"),
        new Song("Feed the Birds", "Mary Poppins"),
        new Song("Practically Perfect", "Mary Poppins"),
        new Song("Supercalifragilistic Expialidocious", "Mary Poppins"),
        new Song("Naughty", "Matilda the Musical"),
        new Song("Hey Good Lookin'", "Mavericks, The"),
        new Song("U Can't Touch This", "MC Hammer"),
        new Song("Motor Psycho", "Megadeth"),
        new Song("Baby's Got Her Blue Jeans On", "Mel McDaniel"),
        new Song("Brand New Key", "Melania Safka"),
        new Song("Bring Me Some Water", "Melissa Etheridge"),
        new Song("Come To My Window", "Melissa Etheridge"),
        new Song("I'm The Only One", "Melissa Etheridge"),
        new Song("Your Heart Is As Black As Night", "Melody Gardot"),
        new Song("Bitch", "Meredith Brooks "),
        new Song("Are The Good Time Really Over", "Merle Haggard"),
        new Song("Big City", "Merle Haggard"),
        new Song("Daddy Frank (The Guitar Man)", "Merle Haggard"),
        new Song("I Think I'll Just Stay Here And Drink", "Merle Haggard"),
        new Song("I'm A Lonesome Fugitive", "Merle Haggard"),
        new Song("Okie From Muskogee", "Merle Haggard"),
        new Song("Ramblin Fever", "Merle Haggard"),
        new Song("Silver Wings", "Merle Haggard"),
        new Song("Sing Me Back Home", "Merle Haggard"),
        new Song("Swinging Doors", "Merle Haggard"),
        new Song("The Bottle Let Me Down", "Merle Haggard"),
        new Song("The Fightin' Side Of Me", "Merle Haggard"),
        new Song("The Way I Am", "Merle Haggard"),
        new Song("Today I Started Loving You Again", "Merle Haggard"),
        new Song("Whiskey In The Jar", "Metallica"),
        new Song("Mad World", "Michael Andrews"),
        new Song("Ave Maria", "Michael Buble"),
        new Song("Cry Me a River", "Michael Buble"),
        new Song("I've Got You Under My Skin", "Michael Buble"),
        new Song("Me and Mrs. Jones", "Michael Buble"),
        new Song("Ben", "Michael Jackson"),
        new Song("Don't Stop 'Til You Get Enough", "Michael Jackson"),
        new Song("Human Nature", "Michael Jackson"),
        new Song("Man In The Mirror", "Michael Jackson"),
        new Song("P.Y.T. (Pretty Young Thing)", "Michael Jackson"),
        new Song("You Are Not Alone", "Michael Jackson"),
        new Song("Stand By Me", "Mickey Gilley"),
        new Song("Grace Kelly", "Mika"),
        new Song("I Took A Pill In Ibiza", "Mike Posner"),
        new Song("I Took A Pill In Ibiza (Seeb Remix)", "Mike Posner"),
        new Song("Adore You", "Miley Cyrus"),
        new Song("Malibu", "Miley Cyrus"),
        new Song("Party In The U.S.A.", "Miley Cyrus"),
        new Song("Down", "Miranda Lambert"),
        new Song("Kerosene", "Miranda Lambert"),
        new Song("Little Red Wagon", "Miranda Lambert"),
        new Song("Tin Man", "Miranda Lambert"),
        new Song("Vice", "Miranda Lambert"),
        new Song("Classic", "MKTO"),
        new Song("Sing It Back", "Moloko"),
        new Song("Always Look On The Bright Side Of Life", "Monty Python"),
        new Song("To Be With You", "Mr. Big"),
        new Song("I'll Make a Man Out of You", "Mulan"),
        new Song("Reflection", "Mulan"),
        new Song("Man or Muppet", "Muppets, The"),
        new Song("Bang Bang (My Baby Shot Me Down)", "Nancy Sinatra"),
        new Song("Summer Wine", "Nancy Sinatra"),
        new Song("(I Love You) For Sentimental Reasons", "Nat King Cole"),
        new Song("Autumn Leaves", "Nat King Cole"),
        new Song("The Christmas Song", "Nat King Cole"),
        new Song("Torn", "Natalie Imbruglia"),
        new Song("I Need Never Get Old", "Nathaniel Rateliff & The Night Sweats"),
        new Song("S.O.B.", "Nathaniel Rateliff & The Night Sweats"),
        new Song("Midnight Train to Georgia", "Neil Diamond"),
        new Song("Breaking Up is Hard to Do", "Neil Sedaka"),
        new Song("Can You Stand The Rain", "New Edition"),
        new Song("All Downhill from Here", "New Found Glory"),
        new Song("Failure's Not Flattering", "New Found Glory"),
        new Song("I Don't Wanna Know", "New Found Glory"),
        new Song("My Friends Over You", "New Found Glory"),
        new Song("Animals", "Nickelback"),
        new Song("How You Remind Me", "Nickelback"),
        new Song("Photograph", "Nickelback"),
        new Song("Rockstar", "Nickelback"),
        new Song("Nemo", "Nightwish"),
        new Song("Over The Hills And Far Away ", "Nightwish"),
        new Song("Sleeping Sun", "Nightwish"),
        new Song("Wish I Had An Angel", "Nightwish"),
        new Song("Jack's Lament", "Nightmare Before Christmas, The"),
        new Song("Oogie Boogie's Song", "Nightmare Before Christmas, The"),
        new Song("Sally's Song", "Nightmare Before Christmas, The"),
        new Song("This is Halloween", "Nightmare Before Christmas, The"),
        new Song("What's This", "Nightmare Before Christmas, The"),
        new Song("I Put a Spell On You", "Nina Simone"),
        new Song("Hand That Feeds", "Nine Inch Nails"),
        new Song("Only ", "Nine Inch Nails"),
        new Song("All Apologies", "Nirvana"),
        new Song("Heart-Shaped Box", "Nirvana"),
        new Song("In Bloom", "Nirvana"),
        new Song("Lake Of Fire", "Nirvana"),
        new Song("Lithium", "Nirvana"),
        new Song("Smells Like Teen Spirit", "Nirvana"),
        new Song("Don't Speak", "No Doubt"),
        new Song("Never Forget You", "Noisettes"),
        new Song("Come Away With Me", "Norah Jones"),
        new Song("Don't Know Why", "Norah Jones"),
        new Song("Sunrise", "Norah Jones"),
        new Song("It's Gonna Be Me", "NSYNC"),
        new Song("Tearin' Up My Heart", "NSYNC"),
        new Song("Party", "Ofenbach"),
        new Song("Consider Yourself", "Oliver!"),
        new Song("Food, Glorious Food", "Oliver!"),
        new Song("Where is Love?", "Oliver!"),
        new Song("Dear Darlin'", "Olly Murs"),
        new Song("What Make You Beautiful", "One Direction"),
        new Song("Love Runs Out", "OneRepublic"),
        new Song("Still The One", "Orleans"),
        new Song("(Sittin' On) The Dock Of The Bay", "Otis Redding"),
        new Song("I've Been Loving You Too Long", "Otis Redding"),
        new Song("Try a Little Tenderness", "Otis Redding"),
        new Song("Your Love", "Outfield, The"),
        new Song("Hey Ya!", "OutKast"),
        new Song("Roses", "OutKast"),
        new Song("Deer in the Headlights", "Owl City"),
        new Song("Fireflies", "Owl City"),
        new Song("Umbrella Beach", "Owl City"),
        new Song("Vanilla Twilight", "Owl City"),
        new Song("Mama, I'm Coming Home", "Ozzy Osbourne"),
        new Song("Make Your Own Kind Of Music", "Paloma Faith"),
        new Song("I Write Sins Not Tragedies", "Panic! At the Disco"),
        new Song("Nine in the Afternoon", "Panic! at the Disco"),
        new Song("This Is Gospel", "Panic! At the Disco"),
        new Song("5 Minutes Alone", "Pantera"),
        new Song("Cemetary Gates", "Pantera"),
        new Song("Cowboys From Hell", "Pantera"),
        new Song("Domination", "Pantera"),
        new Song("F**king Hostile", "Pantera"),
        new Song("The Love", "Pantera"),
        new Song("Walk", "Pantera"),
        new Song("Last Resort", "Papa Roach"),
        new Song("Scars", "Papa Roach"),
        new Song("I Think I Love You", "Partridge Family, The"),
        new Song("Fire and Ice", "Pat Benatar"),
        new Song("Heartbreaker", "Pat Benatar"),
        new Song("We Belong", "Pat Benatar"),
        new Song("Crazy", "Patsy Cline"),
        new Song("Leavin' On Your Mind", "Patsy Cline"),
        new Song("She's Got You", "Patsy Cline"),
        new Song("Sweet Dreams", "Patsy Cline"),
        new Song("Walkin' After Midnight", "Patsy Cline"),
        new Song("Your Cheatin' Heart", "Patsy Cline"),
        new Song("If Only You Knew", "Patti LaBelle"),
        new Song("Diana", "Paul Anka"),
        new Song("Put Your Head On My Shoulder", "Paul Anka"),
        new Song("Come On To Me", "Paul McCartney"),
        new Song("Ebony and Ivory", "Paul McCartney"),
        new Song("My Love", "Paul McCartney"),
        new Song("Reunited", "Peaches And Herb"),
        new Song("Alive", "Pearl Jam"),
        new Song("Black", "Pearl Jam"),
        new Song("Even Flow", "Pearl Jam"),
        new Song("Jeremy", "Pearl Jam"),
        new Song("It's Impossible", "Perry Como"),
        new Song("Mysterious Girl", "Peter Andre"),
        new Song("Downtown", "Petula Clark"),
        new Song("Magic", "Pilot"),
        new Song("Beautiful Trauma", "Pink"),
        new Song("Dear Mr. President", "Pink"),
        new Song("Glitter in the Air", "Pink"),
        new Song("Just Like A Pill", "Pink"),
        new Song("So What", "Pink"),
        new Song("Try", "Pink"),
        new Song("Who Knew", "Pink"),
        new Song("Another Brick In The Wall (part 2)", "Pink Floyd"),
        new Song("Freedom", "Pitbull"),
        new Song("Hey There Delilah", "Plain White T's"),
        new Song("Smoke Gets in Your Eyes", "Platters, The"),
        new Song("Colors of the Wind (End Title)", "Pocahontas"),
        new Song("Just Around the Riverbend", "Pocahontas"),
        new Song("I'm So Excited", "Pointer Sisters, The"),
        new Song("Every Rose Has Its Thorn", "Poison"),
        new Song("Nothing But A Good Time", "Poison"),
        new Song("Something To Believe In", "Poison"),
        new Song("Talk Dirty To Me", "Poison"),
        new Song("Be Still My Heart", "Postal Service, The"),
        new Song("Nothing Better", "Postal Service, The"),
        new Song("The District Sleeps Alone Tonight", "Postal Service, The"),
        new Song("We Will Become Silhouettes", "Postal Service, The"),
        new Song("I Want It That Way", "Postmodern Jukebox"),
        new Song("Peaches", "Presidents of the United States of America, The"),
        new Song("Don't Get Me Wrong", "Pretenders, The"),
        new Song("Amie", "Pure Prairie League"),
        new Song("Harden My Heart", "Quarterflash"),
        new Song("A King Of Magic", "Queen"),
        new Song("Another One Bites the Dust", "Queen"),
        new Song("Bohemian Rhapsody", "Queen"),
        new Song("Bohemian Rhapsody (short version)", "Queen"),
        new Song("Crazy Little Thing Called Love", "Queen"),
        new Song("Don't Stop Me Now", "Queen"),
        new Song("Fat Bottomed Girls", "Queen"),
        new Song("Good Old-Fashioned Lover Boy", "Queen"),
        new Song("I Want to Break Free", "Queen"),
        new Song("Killer Queen", "Queen"),
        new Song("Love Of My Life", "Queen"),
        new Song("Radio Ga Ga", "Queen"),
        new Song("Somebody to Love", "Queen"),
        new Song("The Show Must Go On", "Queen"),
        new Song("We are the Champions", "Queen"),
        new Song("Who Wants to Live Forever", "Queen"),
        new Song("We Will Rock You", "Queen"),
        new Song("You're My Best Friend", "Queen"),
        new Song("Losing My Religion", "R.E.M."),
        new Song("Love You More", "Racoon"),
        new Song("He Walked On Water", "Randy Travis"),
        new Song("Bless The Broken Road", "Rascal Flatts"),
        new Song("I Won't Let Go", "Rascal Flatts"),
        new Song("Life is a Highway", "Rascal Flatts"),
        new Song("Hallelujah I Love Her So", "Ray Charles"),
        new Song("Heartaches by the Number", "Ray Price"),
        new Song("My Shoes Keep Walking Back to You", "Ray Price"),
        new Song("You to Me Are Everything", "Real Thing, The"),
        new Song("How Blue", "Reba McEntire"),
        new Song("One Song Glory", "Rent"),
        new Song("Out Tonight", "Rent"),
        new Song("Seasons Of Love", "Rent"),
        new Song("Take Me or Leave Me", "Rent"),
        new Song("Right Here Waiting", "Richard Marx"),
        new Song("Never Gonna Give You Up", "Rick Astley"),
        new Song("Superfreak", "Rick James"),
        new Song("Jessie's Girl", "Rick Springfield"),
        new Song("She Bangs", "Ricky Martin"),
        new Song("Garden Party", "Ricky Nelson"),
        new Song("Hello Mary Lou", "Ricky Nelson"),
        new Song("Poor Little Fool", "Ricky Nelson"),
        new Song("Travelin' Man", "Ricky Nelson"),
        new Song("Crying My Heart Out Over You", "Ricky Skaggs"),
        new Song("I'll Leave This World Loving You", "Ricky Van Shelton"),
        new Song("Life Turned Her That Way", "Ricky Van Shelton"),
        new Song("Russian Roulette", "Rihanna "),
        new Song("Ready to Fall", "Rise Against"),
        new Song("Swing Life Away", "Rise Against"),
        new Song("Donna", "Ritchie Valens"),
        new Song("Angels (Acoustic)", "Robbie Williams"),
        new Song("Rock DJ", "Robbie Williams"),
        new Song("She's The One", "Robbie Williams"),
        new Song("Addicted To Love", "Robert Palmer"),
        new Song("Every Kinda People", "Robert Palmer"),
        new Song("Somebody's Watching Me", "Rockwell"),
        new Song("(I Can't Get No) Satisfaction", "Rolling Stones, The"),
        new Song("Honky Tonk Women", "Rolling Stones, The"),
        new Song("Sympathy for the Devil", "Rolling Stones, The"),
        new Song("Father and Son", "Ronan Keating"),
        new Song("I Wouldn't Have Missed It For the World", "Ronnie Milsap"),
        new Song("Lost in the Fifties Tonight (In the Still of the Night)", "Ronnie Milsap"),
        new Song("Tennessee Flat Top Box", "Rosanne Cash"),
        new Song("It Must Have Been Love", "Roxette"),
        new Song("Listen to Your Heart", "Roxette"),
        new Song("Blue Bayou", "Roy Orbison"),
        new Song("Crying", "Roy Orbison"),
        new Song("Dream Baby (How Long Must I Dream)", "Roy Orbison"),
        new Song("In Dreams", "Roy Orbison"),
        new Song("Oh, Pretty Woman", "Roy Orbison"),
        new Song("Only The Lonely", "Roy Orbison"),
        new Song("Only The Lonely (Know The Way I Feel) (With The Royal Philharmonic Orchestra)", "Roy Orbison"),
        new Song("Hallelujah", "Rufus Wainwright"),
        new Song("It's Tricky", "Run-D.M.C."),
        new Song("Walk This Way", "Run-DMC"),
        new Song("Escape (The Pina Colada Song)", "Rupert Holmes"),
        new Song("Reach", "S Club 7"),
        new Song("Eyes Wide Open", "Sabrina Carpenter"),
        new Song("Push It", "Salt' N' Pepa"),
        new Song("Body Like A Back Road", "Sam Hunt"),
        new Song("House Party", "Sam Hunt"),
        new Song("Lil' Red Riding Hood", "Sam The Sham & The Pharaohs"),
        new Song("Help Me Make It Through the Night", "Sammi Smith"),
        new Song("I've Gotta Be Me", "Sammy Davis Jr."),
        new Song("1979", "Samshing Pumpkins, The"),
        new Song("Brave", "Sara Bareilles"),
        new Song("Gravity", "Sara Bareilles"),
        new Song("I Choose You", "Sara Bareilles"),
        new Song("Love Song", "Sara Bareilles"),
        new Song("Angel", "Sarah Mclachlan"),
        new Song("Reach", "S Club 7"),
        new Song("Rock You Like A Hurricane", "Scorpions"),
        new Song("Wind of Change", "Scorpions"),
        new Song("The Man Who Can't Be Moved", "Script, The"),
        new Song("Kiss From A Rose", "Seal"),
        new Song("I'll Never Find Another You", "Seekers, The"),
        new Song("Hands to Myself", "Selena Gomez"),
        new Song("It Wasn't Me", "Shaggy"),
        new Song("Life of the Party", "Shawn Mendes"),
        new Song("There's Nothing Holdin' Me Back", "Shawn Mendes"),
        new Song("The First Cut is the Deepest", "Sheryl Crow"),
        new Song("Simple Man", "Shinedown"),
        new Song("Big Girls Cry", "Sia"),
        new Song("Bird Set Free", "Sia"),
        new Song("Chandelier", "Sia"),
        new Song("Chandelier (Piano Version)", "Sia"),
        new Song("Cheap Thrills", "Sia"),
        new Song("Cheap Thrills (feat. Sean Paul)", "Sia"),
        new Song("Helium", "Sia"),
        new Song("Never Give Up", "Sia"),
        new Song("Astronaut", "Simple Plan"),
        new Song("Don't Wanna Think About You", "Simple Plan"),
        new Song("Jet Lag (FT Marie-Mai)(French Version)", "Simple Plan"),
        new Song("Jet Lag (FT Natasha Bedingfield)", "Simple Plan"),
        new Song("Shut Up", "Simple Plan"),
        new Song("Summer Paradise", "Simple Plan"),
        new Song("Welcome to my Life", "Simple Plan"),
        new Song("Hallelujah", "Sing"),
        new Song("Set It All Free", "Sing"),
        new Song("Good Morning", "Singin' In The Rain"),
        new Song("Singin' In The Rain", "Singin' In The Rain"),
        new Song("Baby Got Back", "Sir Mix-a-Lot"),
        new Song("We Are Family", "Sister Sledge"),
        new Song("Kiss Me", "Sixpence None the Richer"),
        new Song("18 And Life", "Skid Row"),
        new Song("Bittersweet Symphony", "Smash "),
        new Song("Broadway, Here I Come!", "Smash "),
        new Song("Let Me Be Your Star", "Smash "),
        new Song("They Just Keep Moving The Line", "Smash "),
        new Song("This Charming Man", "Smiths, The"),
        new Song("Living Next Door To Alice", "Smokie"),
        new Song("Rhythm Is A Dancer", "Snap!"),
        new Song("Gin and Juice", "Snoop Dogg"),
        new Song("Sweat (David Guetta Remix)", "Snoop Dogg"),
        new Song("I Am A Man Of Constant Sorry", "Soggy Bottom Boys"),
        new Song("Cry To Me", "Solomon Burke"),
        new Song("I Got You Babe", "Sonny & Cher"),
        new Song("Runaway Train", "Soul Asylum"),
        new Song("Black Hole Sun", "Soundgarden"),
        new Song("Burden in My Hand", "Soundgarden"),
        new Song("Fell on Black Days", "Soundgarden"),
        new Song("Outshined", "Soundgarden"),
        new Song("Goodnight, Sweetheart, Goodnight", "Spaniels, The"),
        new Song("Keep On Running", "Spencer Davis Group, The"),
        new Song("All I Want For Christmas Is My Two Front Teeth", "Spike Jones"),
        new Song("Two Princes", "Spin Doctors"),
        new Song("Could It Be I'm Falling in Love", "Spinners, The"),
        new Song("I'll Be Around", "Spinners, The"),
        new Song("It's Been Awhile", "Staind"),
        new Song("Outside", "Staind"),
        new Song("So Far Away", "Staind"),
        new Song("Tangled Up In You", "Staind"),
        new Song("We Built This City", "Starship"),
        new Song("Dirty Work", "Steely Dan"),
        new Song("Rikki Don't Lose That Number", "Steely Dan"),
        new Song("Born To Be Wild", "Steppenwolf"),
        new Song("Magic Carpet Ride", "Steppenwolf"),
        new Song("Dakota", "Stereophonics"),
        new Song("Copperhead Road", "Steve Earle"),
        new Song("Galway Girl", "Steve Earle"),
        new Song("Edge Of Seventeen", "Stevie Nicks"),
        new Song("Texas Flood", "Stevie Ray Vaughan"),
        new Song("A Place In The Sun", "Stevie Wonder"),
        new Song("For Once in My Life", "Stevie Wonder"),
        new Song("Big Empty", "Stone Temple Pilots"),
        new Song("Creep", "Stone Temple Pilots"),
        new Song("Interstate Love Song", "Stone Temple Pilots"),
        new Song("Plush", "Stone Temple Pilots"),
        new Song("Plush (Acoustic)", "Stone Temple Pilots"),
        new Song("Vasoline", "Stone Temple Pilots"),
        new Song("Wicked Garden", "Stone Temple Pilots"),
        new Song("Last Nite", "Strokes, The"),
        new Song("Reptillia", "Strokes, The"),
        new Song("I'm Stone in Love with You", "Stylistics, The"),
        new Song("You Make Me Feel Brand New", "Stylistics, The"),
        new Song("Come Sail Away", "Styx"),
        new Song("Badfish", "Sublime"),
        new Song("Smoke Two Joints", "Sublime"),
        new Song("What I Got", "Sublime"),
        new Song("Fly", "Sugar Ray"),
        new Song("Fat Lip", "Sum 41"),
        new Song("In Too Deep", "Sum 41"),
        new Song("Pieces", "Sum 41"),
        new Song("Some Say", "Sum 41"),
        new Song("Still Waiting", "Sum 41"),
        new Song("Breakfast In America", "Supertramp"),
        new Song("Goodbye Stranger", "Supertramp"),
        new Song("The Logical Song", "Supertramp"),
        new Song("Stop! In the Name of Love", "Supremes, The"),
        new Song("Ballroom Blitz", "Sweet"),
        new Song("Dare You to Move", "Switchfoot"),
        new Song("Right Here (Human Nature Radio Mix)", "SWV"),
        new Song("Nobody", "Sylvia"),
        new Song("A Million Love Songs", "Take That"),
        new Song("Back For Good", "Take That"),
        new Song("Cute without the \"E\" (Cut from the Team)", "Taking Back Sunday"),
        new Song("Stand By Your Man", "Tammy Wynette"),
        new Song("I See the Light", "Tangled"),
        new Song("Mother Knows Best", "Tangled"),
        new Song("When Will My Life Begin", "Tangled"),
        new Song("San Antonio Stroll", "Tanya Tucker"),
        new Song("Everybody Wants To Rule The World", "Tears For Fears"),
        new Song("Shout", "Tears For Fears"),
        new Song("Close the Door", "Teddy Pendergrass"),
        new Song("Hunger Strike", "Temple Of The Dog"),
        new Song("Say Hello 2 Heaven", "Temple of the Dog"),
        new Song("Ain't Too Proud To Beg", "Temptations, The"),
        new Song("Get Ready", "Temptations, The"),
        new Song("Just My Imagination (Running Away From Me) ", "Temptations, The"),
        new Song("My Girl", "Temptations, The"),
        new Song("The Way You Do the Things You Do", "Temptations, The"),
        new Song("Double Team", "Tenacious D"),
        new Song("History", "Tenacious D"),
        new Song("Kickapoo", "Tenacious D"),
        new Song("Low Hangin' Fruit", "Tenacious D"),
        new Song("Rock Is Dead", "Tenacious D"),
        new Song("Tribute", "Tenacious D"),
        new Song("Wonderboy", "Tenacious D"),
        new Song("(Hey Baby) Que Paso", "Texas Tornados"),
        new Song("Chocolate", "The 1975"),
        new Song("The Sound", "The 1975"),
        new Song("One Less Bell to Answer", "The 5th Dimension"),
        new Song("Bad Girlfriend", "Theory Of A Deadman"),
        new Song("Humble And Kind", "Tim McGraw"),
        new Song("Just To See You Smile", "Tim McGraw"),
        new Song("Apologize", "Timbaland"),
        new Song("Nutbush City Limits", "Tina Turner"),
        new Song("Proud Mary", "Tina Turner"),
        new Song("Steamy Windows", "Tina Turner"),
        new Song("We Don't Need Another Hero", "Tina Turner"),
        new Song("Waterfalls", "TLC"),
        new Song("Possum Kingdom", "Toadies, The"),
        new Song("Should've Been A Cowboy", "Toby Keither"),
        new Song("Delilah", "Tom Jones"),
        new Song("She's a Lady", "Tom Jones"),
        new Song("What's New Pussycat?", "Tom Jones"),
        new Song("Another Love", "Tom Odell"),
        new Song("American Girl", "Tom Petty"),
        new Song("I Like Beer", "Tom T. Hall"),
        new Song("Old Dogs, Children And Watermelon Wine", "Tom T. Hall"),
        new Song("Crystal Blue Persuasion", "Tommy James And The Shondells"),
        new Song("Mickey", "Toni Basil"),
        new Song("Talking Body", "Tove Lo"),
        new Song("Watermelon Crawl", "Tracy Byrd"),
        new Song("Time Marches On", "Tracy Lawrence"),
        new Song("Drops Of Jupiter (Tell Me)", "Train"),
        new Song("Anymore", "Travis Tritt"),
        new Song("Here's A Quarter (Call Someone Who Cares)", "Travis Tritt"),
        new Song("She's in Love with the Boy", "Trisha Yearwood"),
        new Song("Wild Thing", "Troggs, The"),
        new Song("Car Radio", "Twenty One Pilots"),
        new Song("House of Gold", "Twenty One Pilots"),
        new Song("Jumpsuit", "Twenty One Pilots"),
        new Song("Lane Boy", "Twenty One Pilots"),
        new Song("Migraine", "Twenty One Pilots"),
        new Song("Ride", "Twenty One Pilots"),
        new Song("Stressed Out", "Twenty One Pilots"),
        new Song("Tear In My Heart", "Twenty One Pilots"),
        new Song("We're Not Gonna Take it", "Twisted Sister"),
        new Song("Black No.1 (Little Miss Scare-All)", "Type O Negative"),
        new Song("Drift Away", "Uncle Kracker"),
        new Song("Climax", "Usher"),
        new Song("OMG", "Usher"),
        new Song("U Remind Me", "Usher"),
        new Song("Ice Cream Man", "Van Halen"),
        new Song("A Thousand Miles", "Vanessa Carlton "),
        new Song("You Really Got Me", "Van Halen"),
        new Song("Fall To Pieces", "Velvet Revolver"),
        new Song("Slither", "Velvet Revolver"),
        new Song("Shalala Lala", "Vengaboys"),
        new Song("Everything You Want", "Vertical Horizon"),
        new Song("Go Rest High On That Mountain", "Vince Gill"),
        new Song("Blister in the Sun", "Violent Femmes, The"),
        new Song("One Foot", "Walk the Moon"),
        new Song("Shut Up And Dance", "Walk The Moon"),
        new Song("Low Rider", "War"),
        new Song("Are You Sure Hank Done It This Way", "Waylon Jennings"),
        new Song("Can't Feel My Face", "Weeknd, The"),
        new Song("Earned It", "Weeknd, The"),
        new Song("Here I Go Again", "Whitesnake"),
        new Song("Greatest Love Of All", "Whitney Houston"),
        new Song("I Wanna Dance With Somebody", "Whitney Houston"),
        new Song("My Love Is Your Love", "Whitney Houston"),
        new Song("Saving All My Love For You", "Whitney Houston"),
        new Song("Always On My Mind", "Willie Nelson"),
        new Song("Angel Flying Too Close To The Ground", "Willie Nelson"),
        new Song("Blue Eyes Crying in the Rain", "Willie Nelson"),
        new Song("Crazy", "Willie Nelson"),
        new Song("Good Hearted Woman", "Willie Nelson"),
        new Song("Mammas Don't Let Your Babies Grow Up To Be Cowboys", "Willie Nelson"),
        new Song("My Heroes Have Always Been Cowboys", "Willie Nelson"),
        new Song("Seven Spanish Angels", "Willie Nelson"),
        new Song("Home (Finale)", "Wiz, The"),
        new Song("I Wish It Could Be Christmas Everyday", "Wizzard"),
        new Song("Renegades", "X Ambassadors"),
        new Song("Unsteady", "X Ambassadors"),
        new Song("Maps", "Yeah Yeah Yeahs"),
        new Song("Desire", "Years & Years"),
        new Song("Ocean Avenue", "Yellowcard"),
        new Song("Try Everything", "Zootopia"),
        new Song("Gimme All Your Lovin'", "ZZ Top"),
        new Song("Tush", "ZZ Top")
    ];
}
